name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Refresh content manifests
        run: python3 scripts/update_news_projects_manifest.py

      - name: Commit manifest updates
        if: github.actor != 'github-actions[bot]'
        run: |
          if git diff --quiet -- public/content/news/index.json public/content/projects/index.json; then
            echo "Content manifests already up to date."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/content/news/index.json public/content/projects/index.json
          git commit -m "chore: refresh content manifests"
          git push

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

          
      - name: Inject post endpoints
        run: |
            cat <<'EOF' > .env
            VITE_POST_AUTH_URL=${{ secrets.VITE_POST_AUTH_URL }}
            VITE_POST_PUBLISH_URL=${{ secrets.VITE_POST_PUBLISH_URL }}
            EOF
        shell: bash

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-mod-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-mod-

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
